// flow-typed signature: bf2f94d96b90b1c19772347981b48f76
// flow-typed version: <<STUB>>/react-select-plus_v^1.0.0-rc.10.patch1/flow_v0.60.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-select-plus'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-select-plus' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-select-plus/dist/react-select-plus.es' {
  declare module.exports: any;
}

declare module 'react-select-plus/dist/react-select-plus' {
  declare module.exports: any;
}

declare module 'react-select-plus/dist/react-select-plus.min' {
  declare module.exports: any;
}

declare module 'react-select-plus/examples/src/app' {
  declare module.exports: any;
}

declare module 'react-select-plus/examples/src/components/BooleanSelect' {
  declare module.exports: any;
}

declare module 'react-select-plus/examples/src/components/Cities' {
  declare module.exports: any;
}

declare module 'react-select-plus/examples/src/components/Contributors' {
  declare module.exports: any;
}

declare module 'react-select-plus/examples/src/components/Creatable' {
  declare module.exports: any;
}

declare module 'react-select-plus/examples/src/components/CustomComponents' {
  declare module.exports: any;
}

declare module 'react-select-plus/examples/src/components/CustomRender' {
  declare module.exports: any;
}

declare module 'react-select-plus/examples/src/components/GithubUsers' {
  declare module.exports: any;
}

declare module 'react-select-plus/examples/src/components/GroupedOptionsField' {
  declare module.exports: any;
}

declare module 'react-select-plus/examples/src/components/Multiselect' {
  declare module.exports: any;
}

declare module 'react-select-plus/examples/src/components/NumericSelect' {
  declare module.exports: any;
}

declare module 'react-select-plus/examples/src/components/States' {
  declare module.exports: any;
}

declare module 'react-select-plus/examples/src/components/Virtualized' {
  declare module.exports: any;
}

declare module 'react-select-plus/examples/src/data/cities' {
  declare module.exports: any;
}

declare module 'react-select-plus/examples/src/data/contributors' {
  declare module.exports: any;
}

declare module 'react-select-plus/examples/src/data/states' {
  declare module.exports: any;
}

declare module 'react-select-plus/examples/src/data/users' {
  declare module.exports: any;
}

declare module 'react-select-plus/lib/Async' {
  declare module.exports: any;
}

declare module 'react-select-plus/lib/AsyncCreatable' {
  declare module.exports: any;
}

declare module 'react-select-plus/lib/Creatable' {
  declare module.exports: any;
}

declare module 'react-select-plus/lib/Dropdown' {
  declare module.exports: any;
}

declare module 'react-select-plus/lib/index' {
  declare module.exports: any;
}

declare module 'react-select-plus/lib/Option' {
  declare module.exports: any;
}

declare module 'react-select-plus/lib/OptionGroup' {
  declare module.exports: any;
}

declare module 'react-select-plus/lib/Select' {
  declare module.exports: any;
}

declare module 'react-select-plus/lib/utils/defaultArrowRenderer' {
  declare module.exports: any;
}

declare module 'react-select-plus/lib/utils/defaultClearRenderer' {
  declare module.exports: any;
}

declare module 'react-select-plus/lib/utils/defaultFilterOptions' {
  declare module.exports: any;
}

declare module 'react-select-plus/lib/utils/defaultMenuRenderer' {
  declare module.exports: any;
}

declare module 'react-select-plus/lib/utils/stripDiacritics' {
  declare module.exports: any;
}

declare module 'react-select-plus/lib/Value' {
  declare module.exports: any;
}

declare module 'react-select-plus/package-scripts' {
  declare module.exports: any;
}

declare module 'react-select-plus/rollup.config' {
  declare module.exports: any;
}

declare module 'react-select-plus/src/Async' {
  declare module.exports: any;
}

declare module 'react-select-plus/src/AsyncCreatable' {
  declare module.exports: any;
}

declare module 'react-select-plus/src/Creatable' {
  declare module.exports: any;
}

declare module 'react-select-plus/src/Dropdown' {
  declare module.exports: any;
}

declare module 'react-select-plus/src/index' {
  declare module.exports: any;
}

declare module 'react-select-plus/src/index.umd' {
  declare module.exports: any;
}

declare module 'react-select-plus/src/Option' {
  declare module.exports: any;
}

declare module 'react-select-plus/src/OptionGroup' {
  declare module.exports: any;
}

declare module 'react-select-plus/src/Select' {
  declare module.exports: any;
}

declare module 'react-select-plus/src/utils/defaultArrowRenderer' {
  declare module.exports: any;
}

declare module 'react-select-plus/src/utils/defaultClearRenderer' {
  declare module.exports: any;
}

declare module 'react-select-plus/src/utils/defaultFilterOptions' {
  declare module.exports: any;
}

declare module 'react-select-plus/src/utils/defaultMenuRenderer' {
  declare module.exports: any;
}

declare module 'react-select-plus/src/utils/stripDiacritics' {
  declare module.exports: any;
}

declare module 'react-select-plus/src/Value' {
  declare module.exports: any;
}

declare module 'react-select-plus/test/Async-test' {
  declare module.exports: any;
}

declare module 'react-select-plus/test/AsyncCreatable-test' {
  declare module.exports: any;
}

declare module 'react-select-plus/test/Creatable-test' {
  declare module.exports: any;
}

declare module 'react-select-plus/test/Select-test' {
  declare module.exports: any;
}

declare module 'react-select-plus/test/Value-test' {
  declare module.exports: any;
}

declare module 'react-select-plus/testHelpers/jsdomHelper' {
  declare module.exports: any;
}

declare module 'react-select-plus/testHelpers/nodeListType' {
  declare module.exports: any;
}

declare module 'react-select-plus/wallaby' {
  declare module.exports: any;
}

declare module 'react-select-plus/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-select-plus/dist/react-select-plus.es.js' {
  declare module.exports: $Exports<'react-select-plus/dist/react-select-plus.es'>;
}
declare module 'react-select-plus/dist/react-select-plus.js' {
  declare module.exports: $Exports<'react-select-plus/dist/react-select-plus'>;
}
declare module 'react-select-plus/dist/react-select-plus.min.js' {
  declare module.exports: $Exports<'react-select-plus/dist/react-select-plus.min'>;
}
declare module 'react-select-plus/examples/src/app.js' {
  declare module.exports: $Exports<'react-select-plus/examples/src/app'>;
}
declare module 'react-select-plus/examples/src/components/BooleanSelect.js' {
  declare module.exports: $Exports<'react-select-plus/examples/src/components/BooleanSelect'>;
}
declare module 'react-select-plus/examples/src/components/Cities.js' {
  declare module.exports: $Exports<'react-select-plus/examples/src/components/Cities'>;
}
declare module 'react-select-plus/examples/src/components/Contributors.js' {
  declare module.exports: $Exports<'react-select-plus/examples/src/components/Contributors'>;
}
declare module 'react-select-plus/examples/src/components/Creatable.js' {
  declare module.exports: $Exports<'react-select-plus/examples/src/components/Creatable'>;
}
declare module 'react-select-plus/examples/src/components/CustomComponents.js' {
  declare module.exports: $Exports<'react-select-plus/examples/src/components/CustomComponents'>;
}
declare module 'react-select-plus/examples/src/components/CustomRender.js' {
  declare module.exports: $Exports<'react-select-plus/examples/src/components/CustomRender'>;
}
declare module 'react-select-plus/examples/src/components/GithubUsers.js' {
  declare module.exports: $Exports<'react-select-plus/examples/src/components/GithubUsers'>;
}
declare module 'react-select-plus/examples/src/components/GroupedOptionsField.js' {
  declare module.exports: $Exports<'react-select-plus/examples/src/components/GroupedOptionsField'>;
}
declare module 'react-select-plus/examples/src/components/Multiselect.js' {
  declare module.exports: $Exports<'react-select-plus/examples/src/components/Multiselect'>;
}
declare module 'react-select-plus/examples/src/components/NumericSelect.js' {
  declare module.exports: $Exports<'react-select-plus/examples/src/components/NumericSelect'>;
}
declare module 'react-select-plus/examples/src/components/States.js' {
  declare module.exports: $Exports<'react-select-plus/examples/src/components/States'>;
}
declare module 'react-select-plus/examples/src/components/Virtualized.js' {
  declare module.exports: $Exports<'react-select-plus/examples/src/components/Virtualized'>;
}
declare module 'react-select-plus/examples/src/data/cities.js' {
  declare module.exports: $Exports<'react-select-plus/examples/src/data/cities'>;
}
declare module 'react-select-plus/examples/src/data/contributors.js' {
  declare module.exports: $Exports<'react-select-plus/examples/src/data/contributors'>;
}
declare module 'react-select-plus/examples/src/data/states.js' {
  declare module.exports: $Exports<'react-select-plus/examples/src/data/states'>;
}
declare module 'react-select-plus/examples/src/data/users.js' {
  declare module.exports: $Exports<'react-select-plus/examples/src/data/users'>;
}
declare module 'react-select-plus/lib/Async.js' {
  declare module.exports: $Exports<'react-select-plus/lib/Async'>;
}
declare module 'react-select-plus/lib/AsyncCreatable.js' {
  declare module.exports: $Exports<'react-select-plus/lib/AsyncCreatable'>;
}
declare module 'react-select-plus/lib/Creatable.js' {
  declare module.exports: $Exports<'react-select-plus/lib/Creatable'>;
}
declare module 'react-select-plus/lib/Dropdown.js' {
  declare module.exports: $Exports<'react-select-plus/lib/Dropdown'>;
}
declare module 'react-select-plus/lib/index.js' {
  declare module.exports: $Exports<'react-select-plus/lib/index'>;
}
declare module 'react-select-plus/lib/Option.js' {
  declare module.exports: $Exports<'react-select-plus/lib/Option'>;
}
declare module 'react-select-plus/lib/OptionGroup.js' {
  declare module.exports: $Exports<'react-select-plus/lib/OptionGroup'>;
}
declare module 'react-select-plus/lib/Select.js' {
  declare module.exports: $Exports<'react-select-plus/lib/Select'>;
}
declare module 'react-select-plus/lib/utils/defaultArrowRenderer.js' {
  declare module.exports: $Exports<'react-select-plus/lib/utils/defaultArrowRenderer'>;
}
declare module 'react-select-plus/lib/utils/defaultClearRenderer.js' {
  declare module.exports: $Exports<'react-select-plus/lib/utils/defaultClearRenderer'>;
}
declare module 'react-select-plus/lib/utils/defaultFilterOptions.js' {
  declare module.exports: $Exports<'react-select-plus/lib/utils/defaultFilterOptions'>;
}
declare module 'react-select-plus/lib/utils/defaultMenuRenderer.js' {
  declare module.exports: $Exports<'react-select-plus/lib/utils/defaultMenuRenderer'>;
}
declare module 'react-select-plus/lib/utils/stripDiacritics.js' {
  declare module.exports: $Exports<'react-select-plus/lib/utils/stripDiacritics'>;
}
declare module 'react-select-plus/lib/Value.js' {
  declare module.exports: $Exports<'react-select-plus/lib/Value'>;
}
declare module 'react-select-plus/package-scripts.js' {
  declare module.exports: $Exports<'react-select-plus/package-scripts'>;
}
declare module 'react-select-plus/rollup.config.js' {
  declare module.exports: $Exports<'react-select-plus/rollup.config'>;
}
declare module 'react-select-plus/src/Async.js' {
  declare module.exports: $Exports<'react-select-plus/src/Async'>;
}
declare module 'react-select-plus/src/AsyncCreatable.js' {
  declare module.exports: $Exports<'react-select-plus/src/AsyncCreatable'>;
}
declare module 'react-select-plus/src/Creatable.js' {
  declare module.exports: $Exports<'react-select-plus/src/Creatable'>;
}
declare module 'react-select-plus/src/Dropdown.js' {
  declare module.exports: $Exports<'react-select-plus/src/Dropdown'>;
}
declare module 'react-select-plus/src/index.js' {
  declare module.exports: $Exports<'react-select-plus/src/index'>;
}
declare module 'react-select-plus/src/index.umd.js' {
  declare module.exports: $Exports<'react-select-plus/src/index.umd'>;
}
declare module 'react-select-plus/src/Option.js' {
  declare module.exports: $Exports<'react-select-plus/src/Option'>;
}
declare module 'react-select-plus/src/OptionGroup.js' {
  declare module.exports: $Exports<'react-select-plus/src/OptionGroup'>;
}
declare module 'react-select-plus/src/Select.js' {
  declare module.exports: $Exports<'react-select-plus/src/Select'>;
}
declare module 'react-select-plus/src/utils/defaultArrowRenderer.js' {
  declare module.exports: $Exports<'react-select-plus/src/utils/defaultArrowRenderer'>;
}
declare module 'react-select-plus/src/utils/defaultClearRenderer.js' {
  declare module.exports: $Exports<'react-select-plus/src/utils/defaultClearRenderer'>;
}
declare module 'react-select-plus/src/utils/defaultFilterOptions.js' {
  declare module.exports: $Exports<'react-select-plus/src/utils/defaultFilterOptions'>;
}
declare module 'react-select-plus/src/utils/defaultMenuRenderer.js' {
  declare module.exports: $Exports<'react-select-plus/src/utils/defaultMenuRenderer'>;
}
declare module 'react-select-plus/src/utils/stripDiacritics.js' {
  declare module.exports: $Exports<'react-select-plus/src/utils/stripDiacritics'>;
}
declare module 'react-select-plus/src/Value.js' {
  declare module.exports: $Exports<'react-select-plus/src/Value'>;
}
declare module 'react-select-plus/test/Async-test.js' {
  declare module.exports: $Exports<'react-select-plus/test/Async-test'>;
}
declare module 'react-select-plus/test/AsyncCreatable-test.js' {
  declare module.exports: $Exports<'react-select-plus/test/AsyncCreatable-test'>;
}
declare module 'react-select-plus/test/Creatable-test.js' {
  declare module.exports: $Exports<'react-select-plus/test/Creatable-test'>;
}
declare module 'react-select-plus/test/Select-test.js' {
  declare module.exports: $Exports<'react-select-plus/test/Select-test'>;
}
declare module 'react-select-plus/test/Value-test.js' {
  declare module.exports: $Exports<'react-select-plus/test/Value-test'>;
}
declare module 'react-select-plus/testHelpers/jsdomHelper.js' {
  declare module.exports: $Exports<'react-select-plus/testHelpers/jsdomHelper'>;
}
declare module 'react-select-plus/testHelpers/nodeListType.js' {
  declare module.exports: $Exports<'react-select-plus/testHelpers/nodeListType'>;
}
declare module 'react-select-plus/wallaby.js' {
  declare module.exports: $Exports<'react-select-plus/wallaby'>;
}
declare module 'react-select-plus/webpack.config.js' {
  declare module.exports: $Exports<'react-select-plus/webpack.config'>;
}
