// flow-typed signature: 7c1cbba4c758f491b58dd9b1ebde5420
// flow-typed version: <<STUB>>/redux-search_v^2.4.0/flow_v0.60.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-search'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-search' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-search/dist/commonjs/actions' {
  declare module.exports: any;
}

declare module 'redux-search/dist/commonjs/constants' {
  declare module.exports: any;
}

declare module 'redux-search/dist/commonjs/index' {
  declare module.exports: any;
}

declare module 'redux-search/dist/commonjs/reducer' {
  declare module.exports: any;
}

declare module 'redux-search/dist/commonjs/reduxSearch' {
  declare module.exports: any;
}

declare module 'redux-search/dist/commonjs/SearchApi' {
  declare module.exports: any;
}

declare module 'redux-search/dist/commonjs/searchMiddleware' {
  declare module.exports: any;
}

declare module 'redux-search/dist/commonjs/selectors' {
  declare module.exports: any;
}

declare module 'redux-search/dist/es/actions' {
  declare module.exports: any;
}

declare module 'redux-search/dist/es/constants' {
  declare module.exports: any;
}

declare module 'redux-search/dist/es/index' {
  declare module.exports: any;
}

declare module 'redux-search/dist/es/reducer' {
  declare module.exports: any;
}

declare module 'redux-search/dist/es/reduxSearch' {
  declare module.exports: any;
}

declare module 'redux-search/dist/es/SearchApi' {
  declare module.exports: any;
}

declare module 'redux-search/dist/es/searchMiddleware' {
  declare module.exports: any;
}

declare module 'redux-search/dist/es/selectors' {
  declare module.exports: any;
}

declare module 'redux-search/dist/umd/redux-search' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-search/dist/commonjs/actions.js' {
  declare module.exports: $Exports<'redux-search/dist/commonjs/actions'>;
}
declare module 'redux-search/dist/commonjs/constants.js' {
  declare module.exports: $Exports<'redux-search/dist/commonjs/constants'>;
}
declare module 'redux-search/dist/commonjs/index.js' {
  declare module.exports: $Exports<'redux-search/dist/commonjs/index'>;
}
declare module 'redux-search/dist/commonjs/reducer.js' {
  declare module.exports: $Exports<'redux-search/dist/commonjs/reducer'>;
}
declare module 'redux-search/dist/commonjs/reduxSearch.js' {
  declare module.exports: $Exports<'redux-search/dist/commonjs/reduxSearch'>;
}
declare module 'redux-search/dist/commonjs/SearchApi.js' {
  declare module.exports: $Exports<'redux-search/dist/commonjs/SearchApi'>;
}
declare module 'redux-search/dist/commonjs/searchMiddleware.js' {
  declare module.exports: $Exports<'redux-search/dist/commonjs/searchMiddleware'>;
}
declare module 'redux-search/dist/commonjs/selectors.js' {
  declare module.exports: $Exports<'redux-search/dist/commonjs/selectors'>;
}
declare module 'redux-search/dist/es/actions.js' {
  declare module.exports: $Exports<'redux-search/dist/es/actions'>;
}
declare module 'redux-search/dist/es/constants.js' {
  declare module.exports: $Exports<'redux-search/dist/es/constants'>;
}
declare module 'redux-search/dist/es/index.js' {
  declare module.exports: $Exports<'redux-search/dist/es/index'>;
}
declare module 'redux-search/dist/es/reducer.js' {
  declare module.exports: $Exports<'redux-search/dist/es/reducer'>;
}
declare module 'redux-search/dist/es/reduxSearch.js' {
  declare module.exports: $Exports<'redux-search/dist/es/reduxSearch'>;
}
declare module 'redux-search/dist/es/SearchApi.js' {
  declare module.exports: $Exports<'redux-search/dist/es/SearchApi'>;
}
declare module 'redux-search/dist/es/searchMiddleware.js' {
  declare module.exports: $Exports<'redux-search/dist/es/searchMiddleware'>;
}
declare module 'redux-search/dist/es/selectors.js' {
  declare module.exports: $Exports<'redux-search/dist/es/selectors'>;
}
declare module 'redux-search/dist/umd/redux-search.js' {
  declare module.exports: $Exports<'redux-search/dist/umd/redux-search'>;
}
