export const FETCH_CHARACTER_REQUEST = 'FETCH_CHARACTER_REQUEST';
export const FETCH_CHARACTER_SUCCESS = 'FETCH_CHARACTER_SUCCESS';
export const FETCH_CHARACTER_FAILURE = 'FETCH_CHARACTER_FAILURE';

export const FETCH_ACHIEVEMENTS_REQUEST = 'FETCH_ACHIEVEMENTS_REQUEST';
export const FETCH_ACHIEVEMENTS_SUCCESS = 'FETCH_ACHIEVEMENTS_SUCCESS';
export const FETCH_ACHIEVEMENTS_FAILURE = 'FETCH_ACHIEVEMENTS_FAILURE';

export const FETCH_CRITERIA_REQUEST = 'FETCH_CRITERIA_REQUEST';
export const FETCH_CRITERIA_SUCCESS = 'FETCH_CRITERIA_SUCCESS';
export const FETCH_CRITERIA_FAILURE = 'FETCH_CRITERIA_FAILURE';

export const FETCH_REALMS_REQUEST = 'FETCH_REALMS_REQUEST';
export const FETCH_REALMS_SUCCESS = 'FETCH_REALMS_SUCCESS';
export const FETCH_REALMS_FAILURE = 'FETCH_REALMS_FAILURE';

export const SET_BASE_URL = 'SET_BASE_URL';
export const SET_REGION = 'SET_REGION';
export const HYDRATE_ACHIEVEMENTS = 'HYDRATE_ACHIEVEMENTS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
