export const FETCH_CHARACTER = 'FETCH_CHARACTER';
export const FETCH_CHARACTER_SUCCESS = 'FETCH_CHARACTER_SUCCESS';
export const FETCH_CHARACTER_FAILURE = 'FETCH_CHARACTER_FAILURE';

export const IMPORT_CATEGORIES = 'IMPORT_CATEGORIES';

export const IMPORT_REALMS = 'IMPORT_REALMS';
